SYSTEM:
  DEVICE: 'cuda:2'
  EXP_NAME: 'base_exp_optuna'
  WAIT_TIME: 50
SOLVER:
  BATCH_SIZE: 2
  NUM_IMG: 10
  NUM_MAPS: 3
  IMG_SIZE: (128, 128)
  EPOCHS: 1
  OPTIMIZER: 'Adam'
  BETAS: (0.90, 0.99)
  LR: 0.0001
  SCHEDULER: 'StepLR'
  STEP_SIZE: 10
  FACTOR: 0.1
