SYSTEM:
  DEVICE: 'cuda:2'
  EXP_NAME: 'real'
  WAIT_TIME: 500
  LOG_FREQ: 2
SOLVER:
  BATCH_SIZE: 5
  NUM_IMG: 10
  NUM_MAPS: 3
  IMG_SIZE: (256, 256)
  EPOCHS: 200
  OPTIMIZER: 'Adam'
  BETAS: (0.90, 0.99)
  LR: 0.0001
  PAITENCE: 1000
